{
 "title": "Linksys dd-wrt 3200",
 "description": "dd-wrt dashboard using SNMP data stored in Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(snmp_scrape_duration_seconds{job=~\"snmp\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Uptime / Load Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "timeticks",
   "valueName": "current",
   "targets": [
    { "expr": "sysUpTime" }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssCpuSystem + ssCpuUser" }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (memTotalFree / memTotalReal)"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "laLoadInt{laNames=\"Load-1\"}/100"
    }
   ]
  },
  {
   "title": "System Load (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "laLoadInt{laNames=\"Load-5\"}/100"
    }
   ]
  },
  {
   "title": "System Load (15m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "laLoadInt{laNames=\"Load-15\"}/100"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Wireless Traffic 5 GHz / ath0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "bits/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(irate(ifOutOctets{ifDescr=\"ath0\"}[5m])) * 8",
     "legendFormat": "Outgoing (5 GHz / ath0)"
    },
    {
     "expr": "sum by(status)(irate(ifInOctets{ifDescr=\"ath0\"}[5m])) * 8",
     "legendFormat": "Incoming (5 GHz / ath0)"
    }
   ]
  },
  {
   "title": "Wireless Traffic 2.4 GHz / ath1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "bits/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(irate(ifOutOctets{ifDescr=\"ath1\"}[5m])) * 8",
     "legendFormat": "Outgoing (2.4 GHz / ath1)"
    },
    {
     "expr": "sum by(status)(irate(ifInOctets{ifDescr=\"ath1\"}[5m])) * 8",
     "legendFormat": "Incoming (2.4 GHz / ath1)"
    }
   ]
  },
  {
   "title": "WAN Traffic (eth0)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "bits/sec" }
   ],
   "targets": [
    {
     "expr": "sum by(status)(irate(ifOutOctets{ifDescr=\"eth0\"}[5m])) * 8",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "sum by(status)(irate(ifInOctets{ifDescr=\"eth0\"}[5m])) * 8",
     "legendFormat": "Incoming"
    }
   ]
  },
  { "title": "Basic CPU  / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ssCpuSystem", "legendFormat": "System" },
    { "expr": "ssCpuUser", "legendFormat": "User" },
    { "expr": "ssCpuIdle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "memTotalReal-memTotalFree", "legendFormat": "Used" },
    { "expr": "memTotalFree", "legendFormat": "Free" },
    { "expr": "memTotalSwap", "legendFormat": "Swap" }
   ]
  }
 ]
}